version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.2.2

commands:
  pre-install:
    steps:
      - run: |
          sudo apt-get install dpkg
          wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install azure-functions-core-tools-4

jobs:
  build:
    docker:
      - image: cimg/base:2022.04
    steps:
      - checkout
      - pre-install
      - azure-cli/install
      - run: |
          az login
          cd ./functions
          func azure functionapp publish tc-test-function --force

workflows:
  build-deploy:
    jobs:
      - hold:
          type: approval
      - build:
          requires:
            - hold